// Package hooks installs and implements the git hooks: a pre-push guard against
// pushing to the base branch, and a collision-aware pre-commit notice. The
// installed hooks are thin shims that exec `wt _hook <name>`, so all logic
// lives in the binary (no embedded bash).
package hooks

import (
	"bufio"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/eharriett0/wt/internal/activework"
	"github.com/eharriett0/wt/internal/collide"
	"github.com/eharriett0/wt/internal/config"
	"github.com/eharriett0/wt/internal/gitx"
	"github.com/eharriett0/wt/internal/ui"
)

const sentinel = "wt _hook"

// PrePushInstalled reports whether a wt-managed pre-push hook is present in the
// repo's shared hooks dir — used by `wt doctor` to flag an unguarded repo where
// the base-branch push guard never ran (#76).
func PrePushInstalled(commonDir string) bool {
	b, err := os.ReadFile(filepath.Join(commonDir, "hooks", "pre-push"))
	return err == nil && strings.Contains(string(b), sentinel)
}

// Install writes the pre-push + pre-commit shims into the shared hooks dir
// (covers every worktree of the repo). force overwrites foreign hooks.
func Install(c *config.Config, force bool) error {
	common, err := gitx.CommonDir()
	if err != nil {
		return fmt.Errorf("resolve git common dir: %w", err)
	}
	hooksDir := filepath.Join(common, "hooks")
	if err := os.MkdirAll(hooksDir, 0o755); err != nil {
		return err
	}
	self, err := os.Executable()
	if err != nil || self == "" {
		self = "wt"
	}

	if err := writeShim(filepath.Join(hooksDir, "pre-push"), self, "pre-push", force); err != nil {
		return err
	}

	if frameworkPresent(c.Root, hooksDir) {
		ui.Warn("pre-commit framework detected — not clobbering pre-commit hook")
		ui.Info("add this to .pre-commit-config.yaml instead:")
		fmt.Print(precommitSnippet(self))
	} else if err := writeShim(filepath.Join(hooksDir, "pre-commit"), self, "pre-commit", force); err != nil {
		return err
	}

	ui.OK("hooks installed in %s", hooksDir)
	ui.Info("shared across all worktrees of this repo")
	ui.Info("bypass: HOOK_DISABLE_MAIN_PUSH=1 (push) · HOOK_DISABLE_MULTIWINDOW_CHECK=1 (commit)")
	return nil
}

func writeShim(path, self, hook string, force bool) error {
	body := fmt.Sprintf("#!/bin/sh\n# wt-managed hook — multi-window coordination (see `wt help`).\nexec %q _hook %s \"$@\"\n", self, hook)

	if existing, err := os.ReadFile(path); err == nil {
		if strings.Contains(string(existing), sentinel) {
			// ours — idempotent overwrite (refresh the binary path).
		} else if force {
			_ = os.WriteFile(path+".bak", existing, 0o755)
			ui.Warn("backed up existing %s hook to %s.bak", hook, filepath.Base(path))
		} else {
			ui.Warn("a non-wt %s hook already exists at %s — skipping (use --force to back up + replace)", hook, path)
			return nil
		}
	}
	if err := os.WriteFile(path, []byte(body), 0o755); err != nil {
		return err
	}
	return nil
}

func frameworkPresent(root, hooksDir string) bool {
	for _, f := range []string{".pre-commit-config.yaml", ".pre-commit-config.yml"} {
		if _, err := os.Stat(filepath.Join(root, f)); err == nil {
			return true
		}
	}
	if b, err := os.ReadFile(filepath.Join(hooksDir, "pre-commit")); err == nil {
		s := string(b)
		if strings.Contains(s, "File generated by pre-commit") || strings.Contains(s, "INSTALL_PYTHON") {
			return true
		}
	}
	return false
}

func precommitSnippet(self string) string {
	return fmt.Sprintf(`
  - repo: local
    hooks:
      - id: wt-collision-check
        name: wt multi-window collision check
        entry: %s _hook pre-commit
        language: system
        pass_filenames: false
        always_run: true
`, self)
}

// HookPrePush implements `wt _hook pre-push`. Rejects pushes whose target ref
// is the base branch. Honors HOOK_DISABLE_MAIN_PUSH=1. Reads either the
// pre-commit-framework env vars or the raw pre-push stdin protocol.
func HookPrePush(c *config.Config, stdin io.Reader) int {
	if os.Getenv("HOOK_DISABLE_MAIN_PUSH") == "1" {
		return 0
	}
	base := c.Base

	if rb := os.Getenv("PRE_COMMIT_REMOTE_BRANCH"); rb != "" {
		if rb == "refs/heads/"+base || rb == base {
			rejectPush(base)
			return 1
		}
		return 0
	}

	code := 0
	sc := bufio.NewScanner(stdin)
	for sc.Scan() {
		fields := strings.Fields(sc.Text())
		// <local_ref> <local_sha> <remote_ref> <remote_sha>
		if len(fields) >= 3 && fields[2] == "refs/heads/"+base {
			rejectPush(base)
			code = 1
		}
	}
	return code
}

func rejectPush(base string) {
	ui.Err("REJECTED: direct push to %q is blocked by the wt pre-push guard.", base)
	fmt.Fprintln(os.Stderr, "  Use a branch + PR:  wt new <slug>  →  commit/push  →  gh pr create  →  wt merge-pr <N>")
	fmt.Fprintln(os.Stderr, "  Bypass (genuine intent — rollback/recovery):  HOOK_DISABLE_MAIN_PUSH=1 git push")
}

// HookPreCommit implements `wt _hook pre-commit`. NEVER blocks (always exit 0).
// It surfaces FILE-LEVEL collisions: staged files that another window is also
// touching. Falls back to an informational "other claims exist" note.
func HookPreCommit(c *config.Config) int {
	if os.Getenv("HOOK_DISABLE_MULTIWINDOW_CHECK") == "1" {
		return 0
	}

	staged, _ := gitx.Run("diff", "--cached", "--name-only")
	stagedFiles := nonEmptyLines(staged)

	ws, err := collide.Scan(c)
	if err != nil {
		return 0
	}
	root, _ := gitx.RepoRoot()

	if len(stagedFiles) > 0 {
		if conflicts := collide.CheckPaths(ws, root, stagedFiles); len(conflicts) > 0 {
			// Suppress collisions against stale branches (merged / no open PR) —
			// same liveness rule as `wt check`, so the hook doesn't cry wolf on
			// every commit against long-dead branches that touched the same file.
			live := collide.ClassifyWindows(ws, c.Base, collide.ConflictWindowSet(conflicts), c.MaxAge)
			active, stale := collide.PartitionConflicts(conflicts, live)
			// Shared docs (CLAUDE.md/MEMORY.md) are append-heavy and edited by
			// nearly every window — downgrade them to an advisory so the notice
			// only sounds the alarm on real code overlaps.
			var hard, soft []collide.Conflict
			for _, cf := range active {
				if collide.IsSharedDoc(cf.Path, c.SharedDocs) {
					soft = append(soft, cf)
				} else {
					hard = append(hard, cf)
				}
			}
			if len(hard) > 0 {
				ui.Collision("%d staged file(s) are ALSO being edited by an active window:", len(hard))
				for _, cf := range hard {
					fmt.Fprintf(os.Stderr, "   %s  %s %s %s\n", ui.Bold(cf.Path), ui.Dim("← also"), cf.Window, live[cf.Window].Badge())
				}
				if len(soft) > 0 {
					fmt.Fprintln(os.Stderr, ui.Dim(fmt.Sprintf("   (+%d shared-doc overlap(s) — advisory)", len(soft))))
				}
				if len(stale) > 0 {
					fmt.Fprintln(os.Stderr, ui.Dim(fmt.Sprintf("   (+%d on stale branch(es) — merged / no open PR — ignored)", len(stale))))
				}
				fmt.Fprintln(os.Stderr, ui.Yellow("   Coordinate before committing to avoid a merge collision."))
				fmt.Fprintln(os.Stderr, ui.Dim("   (informational — not blocking · HOOK_DISABLE_MULTIWINDOW_CHECK=1 to silence)"))
				return 0
			}
			if len(soft) > 0 {
				var names []string
				for _, cf := range soft {
					names = append(names, cf.Path)
				}
				fmt.Fprintln(os.Stderr, ui.Dim(fmt.Sprintf("📝 shared doc(s) also edited in another window (advisory; coordinate sections): %s", strings.Join(names, ", "))))
			}
		}
	}

	// No file overlap — cheap awareness of other active claims.
	others := activework.OtherClaims(activework.Read(c.ActiveWork), issueFromBranch(c))
	if len(others) > 0 {
		fmt.Fprintln(os.Stderr, ui.Dim(fmt.Sprintf("📋 %d other active window claim(s): %s", len(others), strings.Join(others, " "))))
	}
	return 0
}

func issueFromBranch(c *config.Config) string {
	br, err := gitx.CurrentBranch()
	if err != nil {
		return ""
	}
	re := regexp.MustCompile(`^` + regexp.QuoteMeta(c.Prefix) + `(\d+)-`)
	if m := re.FindStringSubmatch(br); m != nil {
		return m[1]
	}
	return ""
}

func nonEmptyLines(s string) []string {
	var out []string
	for _, ln := range strings.Split(s, "\n") {
		if ln = strings.TrimSpace(ln); ln != "" {
			out = append(out, ln)
		}
	}
	return out
}
